#! /bin/bash

CMD="zpool status -x"

function no_with_status {
  sudo zpool status -v | grep $1 | wc -l

}

no_online=$(no_with_status ONLINE)
no_degraded=$(no_with_status DEGRADED)
no_faulted=$(no_with_status FAULTED)
no_offline=$(no_with_status OFFLINE)
no_unavailable=$(no_with_status UNAVAILABLE)
no_removed=$(no_with_status REMOVED)
no_actions=$(no_with_status "action:")


case $1 in
   config)
        echo <<EOM "graph_title zpool status
graph_order online degraded faulted offline unavailable removed action
graph_args --base 1024 -r -l 0 --vertical-label Units
graph_info Shows the status of the ZFS node
graph_category Zfs
graph_period second
online.label Online
online.draw LINE1
online.info Online
degraded.label Degraded
degraded.draw LINE1
degraded.info Degraded
degraded.critical 0:0
faulted.label Faulted
faulted.draw LINE1
faulted.info Faulted
faulted.critical 0:0
offline.label Offline
offline.draw LINE1
offline.info Offline
offline.critical 0:0
unavailable.label Unavailable
unavailable.draw LINE1
unavailable.info Unavailable
unavailable.critical 0:0
removed.label Removed
removed.draw LINE1
removed.info Removed
removed.critical 0:0
action.label Actions
action.draw LINE1
action.info Actions
action.critical 0:0"

EOM
        exit 0;;
esac

echo <<EOF "online.value  $no_online
degraded.value $no_degraded
faulted.value $no_faulted
offline.value $no_offline
unavailable.value $no_unavailable
removed.value $no_removed
action.value $no_actions
"
EOF
