#! /usr/bin/env python

import argparse
import socket
from fabric.api import *
from git import *

DTG_DOM = '.dtg.cl.cam.ac.uk'

DOM0    = 'root@husky0' + DTG_DOM

PUPPET_BARE = '/etc/puppet-bare'

PHYSICAL_MACHINES = [ {'name': 'nas01', 'hostname': 'nas01' + DTG_DOM, 'VM': False},
                      {'name': 'entropy', 'hostname': 'entropy' + DTG_DOM, 'VM': False},
                  ]

@task
def get_vms():
    uuids = run('xe vm-list params=uuid PV-bootloader=pygrub --minimal').split(',')
    vms = []
    for uuid in uuids:
        name_label = run('xe vm-list params=name-label uuid=%s --minimal' % uuid).replace(' ','')
        ip = run('xe vm-param-get param-name=networks uuid=%s | sed -e \'s_0/ip: __\' -e  \'s/; .*$//\'' % uuid)
        hostname = socket.gethostbyaddr(ip)[0]

        vms.append({'name':name_label, 'hostname':hostname, 'VM': True, 'uuid':uuid})
    return vms

def get_machines():
    vms = execute(get_vms, hosts=[DOM0])
    return PHYSICAL_MACHINES + vms[DOM0]

@task
def snapshot_mc(mc, commit_id):
    assert mc['VM']
    run('xe vm-snapshot uuid=%s new-name-label=%s' % (mc['uuid'], commit_id))

def add_remotes(repo, machines):
    """
    Delete all remotes, then add those listed in `machines'
    """
    for remote in repo.remotes:
        repo.delete_remote(remote)
        
    for mc in machines:
        new_remote = repo.create_remote(mc['name'], mc['hostname']  + ':' + PUPPET_BARE)

def push_config(repo, mc):
    repo.remotes[mc['name']].push()

        
def main(args):
    repo = Repo('.')
    machines = get_machines()
    add_remotes(repo, machines)
    
    for mc in machines:
        if mc['VM']:
            execute(snapshot_mc, mc, repo.head.commit.hexsha, hosts=[DOM0])
#'        push_config(repo, mc)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Pushes the master branch of dtg-puppet, as found on github all over the world')
    parser.add_argument('--boot', help='Boot linux machines that are currently turned off.')
    args = parser.parse_args()
    main(args)
