#!/bin/sh

# A munin plugin that detects whether the current filesystem has been mounted
# as read only

# Munin is asking for some config output
if [ "$1" = "config" ]; then
    echo 'graph_title FS Readonly'
    echo 'graph_vlabel readonly'
    echo 'graph_catagory system'
    echo 'fs_readonly.label readonly'
    exit 0
fi

echo -n "fs_readonly.value "

mount -t ext4 |cut -f6 -d ' '|cut -f1 -d ','|grep '(ro' > /dev/null
if [ $? -eq 0 ]
then
    echo "1"
    exit 0
fi

mount |grep 'warning'
if [ $? -eq 0 ]
then
    echo "1"
    exit 0
fi

echo "0"

