#!/bin/bash

set -e

USAGE='Usage: ms-does-trust-certifiers <user>'
# Does the user trust the id certifying keys

user=$1
if [$user == '--help'] then
  echo $USAGE
  exit 1 # we have't tested that they do
fi
# Get the list of id certifiers
certifiers=`monkeysphere-authentication list-id-certifiers | grep -v "^ :" | sed s/://`
# Get the key lines of the public keys we ultimately trust
keylines=`sudo -H -u $user gpg --list-keys --with-colons | grep '^pub:u:'`

for certifier in $certifiers; do
  # look for a keyline containing the key id (last 16 characters of fingerprint)
  echo $keylines | grep ${certifier:${#certifier} - 16:16} || exit 1
done

