#!/bin/bash

set -e

# Intended to be run from cron to check that all services have been restarted that need to be after an update.

nonefound="Found 0 processes using old versions of upgraded files"

# Try and automatically restart as much as we can
services=`sudo checkrestart | grep -v "$nonefound" | grep --line-regexp 'service [a-zA-Z0-9\.\-]* restart' | sed 's/service \([a-Z0-9\.\-]*\) restart/\1/'`

if [ ! -z "$services" ]; then
	echo "Restarting services: $services"
fi

for service in $services; do sudo service "$service" restart; done

# If there are still things left then this will output text which will be emailed by cron or displayed to the sysadmin

sudo checkrestart | grep -v "$nonefound"
