#!/bin/sh

# Set the password of the user supplied as the one argument
# the argument must be a crsid valid for cl.cam.ac.uk

USER=$1
PASSWORD=`apg -n1 -M ncl`
chpasswd <<EOF
$USER:$PASSWORD
EOF

MACHINE=`hostname`

mail \
    -a "Reply-to: DTG Code <dtg-infra@cl.cam.ac.uk>" \
    -a "Content-type: text/plain; format=flowed; charset=UTF-8" \
    -a "From: DTG Code <dtg-infra@cl.cam.ac.uk>" \
    -s "Password for $MACHINE" $USER"@cl.cam.ac.uk" <<EOF

Your password as user $USER on machine $MACHINE is:
$PASSWORD

You may want to change it.

EOF
